# Generated by Django 5.1.5 on 2025-01-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttb',
            old_name='Cat_id',
            new_name='Cat',
        ),
    ]
